#pragma once

#define REG_CREATE "create"
#define REG_STRING "string"
#define REG_NUMBER "number"
#define REG_SYMBOL "symbol"
#define REG_FUNCTION "function"
#define REG_RETURN "return"
#define REG_SHOW "show"
#define REG_MAIN "main"
#define REG_ID "[a-z]+"
#define REG_NUMBER_LIT "(0|(-?([1-9]+[0-9]*)))|((0|([1-9]+[0-9]*))e)|((0|([1-9]+[0-9]*))d)"
#define REG_SYMBOL_LIT "'(.)'"
#define REG_STRING_LIT "'(.)*'"
#define REG_SEMICOLON ";"
#define REG_EQUAL "="
#define REG_COMMA ","
#define REG_MREQUAL "\\{"
#define REG_LSEQUAL "\\}"
#define REG_LEFTTHESIS "\\("
#define REG_RIGHTTHESIS "\\)"
#define REG_PLUS "\\+"
#define REG_MINUS "\\-"
#define REG_STAR "\\*"
#define REG_DIRSLASH "/"
#define REF_
#define REG_IF "if"
#define REG_ELSE "else"
#define REG_MORE ">"
#define REG_LESS "<"
#define REG_MORE_OR_EQUALS ">="
#define REG_LESS_OR_EQUALS "<="
#define REG_FULL_EQUALS "=="
#define REG_NOT_FULL_EQUALS "!="